// Generated by FlutterFire CLI.
// Run: flutterfire configure
// This file will be auto-generated when you run `flutterfire configure`
// Replace this file with the one generated by FlutterFire CLI

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static Object get currentPlatform {
    if (kIsWeb) return Object();
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return Object();
      case TargetPlatform.iOS:
        return Object();
      default:
        return Object();
    }
  }

  // ⚠️ Replace ALL values below with your own Firebase project values
  // Get them by running: flutterfire configure

  static const Object web = Object();

  static const Object android = Object();

  static const Object ios = Object();
}